[package]
name = "shuffler"
version = "0.1.0"
authors = ["Umayr Shahid <umayr.shahid@gmail.com>"]
edition = "2018"

[lib]
name = "shuffler"
path = "src/lib.rs"

[[bin]]
name = "shuffler"
path = "src/main.rs"

[dependencies]
rand = "0.8.3"
getopts = "0.2"
