on:
  pull_request:
    types: [opened, synchronize, reopened]

name: Pull Request

jobs:
  test-app:
    name: Test App
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install Deps
        working-directory: ./app
        run: npm install

      - name: Test
        working-directory: ./app
        run: npm test

  test-lib:
    name: Test Library
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
